### ISSUE TITLE
libQt5Test.so.5: undefined reference to

### ISSUE THREAD

**Issue by jackros1022** [ros-industrial/ros_qtc_plugin#117]
17:23:33: Running steps for project view_ws...
17:23:33: Starting: "/opt/ros/kinetic/bin/catkin_make" --cmake-args -G 'CodeBlocks - Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug
[ 12%] Built target kinect2_registration
[ 20%] Built target pcl_filter
[ 28%] Built target kinect2_bridge
[ 36%] Built target kinect2_bridge_nodelet
[ 44%] Built target view_Normal
[ 52%] Built target viewer_process
[ 56%] Linking CXX executable /home/jack/ros/view_ws/devel/lib/kinect2_viewer/kinect2_viewer
[ 64%] Built target cloud_read
[ 72%] Built target seg_euclidean_cluster
[ 80%] Built target fealture_normalEstimation
[ 88%] Built target seg_cylinder
[ 96%] Built target seg_cylinder_no_class
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QListData::realloc(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::connectNotify(QMetaMethod const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::absolutePath() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QProcess::readAllStandardOutput()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::toLongLong(bool*, int) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QWaitCondition::wait(QMutex*, unsigned long)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::customEvent(QEvent*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::append(char)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qInstallMessageHandler(void (*)(QtMsgType, QMessageLogContext const&, QString const&))@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qvsnprintf(char*, unsigned long, char const*, __va_list_tag*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QElapsedTimer::start()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaType::typeName(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QAbstractEventDispatcher::removeNativeEventFilter(QAbstractNativeEventFilter*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QVariant::~QVariant()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::mid(int, int) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::toLocal8Bit_helper(QChar const*, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::operator=(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMutex::lock()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QWaitCondition::QWaitCondition()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::chop(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::objectName() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QAbstractConcatenable::appendLatin1To(char const*, int, QChar*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDir::mkpath(QString const&) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QThread::QThread(QObject*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::operator==(QLatin1String) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qVersion@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QSysInfo::productType()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QSysInfo::productVersion()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qt_version_tag@Qt_5.7'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFile::QFile()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDir::absoluteFilePath(QString const&) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::toLatin1_helper(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::append(char const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QVariant::QVariant(QRegularExpression const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFile::open(QFlags<QIODevice::OpenModeFlag>)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::isNull() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QTemporaryDir::QTemporaryDir()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::split(char) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QVariant::toRegularExpression() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::append(QByteArray const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaObjectPrivate::signal(QMetaObject const*, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::~QObject()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::number(double, char, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::setFile(QDir const&, QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::fromUtf8_helper(char const*, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QLibraryInfo::location(QLibraryInfo::LibraryLocation)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QLibraryInfo::build()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::QFileInfo()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMessageLogger::fatal(char const*, ...) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qstrcmp(QByteArray const&, QByteArray const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::QByteArray(char const*, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::QByteArray(int, Qt::Initialization)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::midRef(int, int) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qFormatLogMessage(QtMsgType, QMessageLogContext const&, QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QProcess::waitForFinished(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::resize(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::killTimer(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QThread::qt_metacast(char const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QIODevice::readLine(long long)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMutex::QMutex(QMutex::RecursionMode)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QListData::dispose(QListData::Data*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QProcess::QProcess(QObject*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::number(double, char, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::fileName() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qstrcmp(char const*, char const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QCoreApplication::self@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::eventFilter(QObject*, QEvent*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::indexOf(QLatin1String, int, Qt::CaseSensitivity) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDir::~QDir()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QVariant::QVariant(QVariant const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::remove(int, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDirIterator::next()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::disconnectNotify(QMetaMethod const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::setFile(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::append(QChar)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::fill(char, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaObject::methodCount() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::fromLatin1_helper(char const*, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::qt_metacall(QMetaObject::Call, int, void**)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::property(char const*) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::arg(long long, int, int, QChar) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFile::open(_IO_FILE*, QFlags<QIODevice::OpenModeFlag>, QFlags<QFileDevice::FileHandleFlag>)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::exists(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaMethod::methodType() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QThread::~QThread()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::qt_metacast(char const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QThread::metaObject() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QAbstractEventDispatcher::installNativeEventFilter(QAbstractNativeEventFilter*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMutex::unlock()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `typeinfo for QAbstractNativeEventFilter@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QWaitCondition::~QWaitCondition()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QListData::detach(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::QString(int, Qt::Initialization)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegExp::~QRegExp()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `operator==(QString const&, QStringRef const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::thread() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::canonicalFilePath() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QElapsedTimer::restart()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QThread::qt_metacall(QMetaObject::Call, int, void**)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaMethod::returnType() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaType::type(char const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QElapsedTimer::elapsed() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::event(QEvent*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QListData::detach_grow(int*, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDir::entryInfoList(QStringList const&, QFlags<QDir::Filter>, QFlags<QDir::SortFlag>) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::operator=(QFileInfo const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMessageLogger::warning(char const*, ...) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QProcess::pid() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::endsWith(QChar, Qt::CaseSensitivity) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaType::create(int, void const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::append(QLatin1String)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFile::remove(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::toInt(bool*, int) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::number(unsigned long long, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QVariant::QVariant(int, void const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QAbstractNativeEventFilter::QAbstractNativeEventFilter()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaObject::method(int) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::filePath() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::fromLocal8Bit_helper(char const*, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `typeinfo for QThread@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::chop(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QTemporaryDir::path() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDirIterator::~QDirIterator()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QAbstractEventDispatcher::instance(QThread*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaMethod::parameterCount() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDir::QDir(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QHashData::allocateNode(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QIODevice::write(char const*, long long)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDirIterator::QDirIterator(QString const&, QFlags<QDirIterator::IteratorFlag>)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegExp::indexIn(QString const&, int, QRegExp::CaretMode) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QTemporaryDir::~QTemporaryDir()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `typeinfo for QObject@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::QFileInfo(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QVariant::toString() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegularExpression::~QRegularExpression()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::toUtf8_helper(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qsnprintf(char*, unsigned long, char const*, ...)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFile::~QFile()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qstrdup(char const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::path() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::isDir() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDirIterator::fileInfo() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qEnvironmentVariableIntValue(char const*, bool*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDirIterator::hasNext() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QProcess::readAllStandardError()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::childEvent(QChildEvent*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QEventLoop::exit(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::staticMetaObject@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QListData::shared_null@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegularExpressionMatch::hasMatch() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::startsWith(char) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QTemporaryDir::isValid() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegularExpressionMatch::~QRegularExpressionMatch()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileDevice::atEnd() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QCoreApplication::applicationDirPath()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QThread::wait(unsigned long)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QArrayData::shared_null@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qt_register_signal_spy_callbacks(QSignalSpyCallbackSet const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qstrncpy(char*, char const*, unsigned int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QElapsedTimer::nsecsElapsed() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegExp::QRegExp(QString const&, Qt::CaseSensitivity, QRegExp::PatternSyntax)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMutex::~QMutex()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDir::exists(QString const&) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObject::timerEvent(QTimerEvent*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QProcess::start(QString const&, QStringList const&, QFlags<QIODevice::OpenModeFlag>)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QListData::append()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::endsWith(char) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMessageLogger::debug(char const*, ...) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegularExpression::isValid() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::isRelative() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::endsWith(char const*) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::simplified_helper(QString&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QProcess::waitForStarted(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QAbstractNativeEventFilter::~QAbstractNativeEventFilter()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegularExpression::match(QString const&, int, QRegularExpression::MatchType, QFlags<QRegularExpression::MatchOption>) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFile::QFile(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::operator=(QLatin1String)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qt_assert_x(char const*, char const*, char const*, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QObjectData::dynamicMetaObject() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::simplified_helper(QByteArray&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaMethod::methodSignature() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QHashData::rehash(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QHashData::shared_null@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFile::setPermissions(QString const&, QFlags<QFileDevice::Permission>)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `operator==(QString const&, QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDir::toNativeSeparators(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaType::destroy(int, void*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::leftRef(int) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::toLower_helper(QString&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QHashData::detach_helper(void (*)(QHashData::Node*, void*), void (*)(QHashData::Node*), int, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qBadAlloc()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QWaitCondition::wakeAll()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::multiArg(int, QString const**) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaMethod::parameterTypes() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::isWritable() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaMethod::name() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaMethod::access() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::arg(double, int, char, int, QChar) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QArrayData::allocate(unsigned long, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qgetenv(char const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QProcess::exitCode() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::arg(QString const&, int, QChar) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFile::copy(QString const&, QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QFileInfo::~QFileInfo()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::insert(int, QChar)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QByteArray::reallocData(unsigned int, QFlags<QArrayData::AllocationOption>)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QVariant::toByteArray() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QHashData::free_helper(void (*)(QHashData::Node*))@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qstrcmp(QByteArray const&, char const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qputenv(char const*, QByteArray const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QProcess::~QProcess()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaObject::indexOfMethod(char const*) const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QArrayData::deallocate(QArrayData*, unsigned long, unsigned long)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QVariant::type() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qt_assert(char const*, char const*, int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegExp::cap(int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QThread::start(QThread::Priority)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qstrcpy(char*, char const*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QCoreApplication::applicationPid()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QTemporaryDir::setAutoRemove(bool)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QDir::currentPath()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QString::append(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `qHash(QByteArray const&, unsigned int)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QMetaObject::className() const@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QVariant::QVariant(QString const&)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QThread::event(QEvent*)@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QThread::currentThread()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QCoreApplication::arguments()@Qt_5'
/opt/qt57/lib/libQt5Test.so.5: undefined reference to `QRegularExpression::pattern() const@Qt_5'
collect2: error: ld returned 1 exit status

can you help me ? please

**Comment by jackros1022** [comment]
do this:
`sudo ln libQt5Test.so.5.7.0 /usr/lib/x86_64-linux-gnu/libQt5Test.so`

haha,it works!

**Comment by JinglinZhang** [comment]
I have the same error, but the ln command doesn't work. 
It seems that the file libQt5Test.so.5.7.0  doesn't exist, and there is already a libQt5Test.so file in /usr/lib/x86_64-linux-gnu/.
Could anyone help?

**Comment by JinglinZhang** [comment]
I delete the original /opt/qt57/lib/libQt5Test.so.5 and make a hard link from /usr/lib/x86_64-linux-gnu/libQt5Test.so.5 to /opt/qt57/lib/libQt5Test.so.5, then it works.
```
$ cd /opt/qt57/lib/
$ cp libQt5Test.so.5 ~/.
$ sudo rm libQt5Test.so.5
$ sudo ln /usr/lib/x86_64-linux-gnu/libQt5Test.so.5  /opt/qt57/lib/libQt5Test.so.5
```

**Comment by Levi-Armstrong** [comment]
I will see what I can do to fix this in the Debian.

**Comment by Levi-Armstrong** [comment]
I have notified the maintainer on launchpad.net.

**Comment by Levi-Armstrong** [comment]
@jackros1022 @JinglinZhang I think this was fixed in the latest release with Qt 5.9 can you confirm?

**Comment by mmoerdijk** [comment]
I still had this problem today, but with the 59 version of qt so this is defently not fixed

**Comment by wutongyu98** [comment]
> I delete the original /opt/qt57/lib/libQt5Test.so.5 and make a hard link from /usr/lib/x86_64-linux-gnu/libQt5Test.so.5 to /opt/qt57/lib/libQt5Test.so.5, then it works.
> 
> ```
> $ cd /opt/qt57/lib/
> $ cp libQt5Test.so.5 ~/.
> $ sudo rm libQt5Test.so.5
> $ sudo ln /usr/lib/x86_64-linux-gnu/libQt5Test.so.5  /opt/qt57/lib/libQt5Test.so.5
> ```

This works well for me. Thanks
