### ISSUE TITLE
I can not download the installer. 

### ISSUE THREAD

**Issue by yunjeongkim** [ros-industrial/ros_qtc_plugin#303]
Hi, I am trying to access the ros plug-in download homepage 

https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/installers/xenial/qtcreator-ros-xenial-latest-online-installer.run

to install qt-ros-plugin, but I couldn't. 

I think the server has a problem. 

Could you fix this problem? Thanks

**Comment by DLuensch** [comment]
> sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial
> sudo add-apt-repository ppa:levi-armstrong/ppa
> sudo apt update && sudo apt install qt57creator
> sudo apt install qt57creator-plugin-ros

I think that should only be a workaround. As mentioned in the tutorial it is not longer recommended to use the ppa. In this case a statement regarding the status of the official download side would be nice.

**Comment by Levi-Armstrong** [comment]
The server is down and we are working to get it backup.

**Comment by Levi-Armstrong** [comment]
Yea, I would recommend against using the ppa it is outdated.

**Comment by Levi-Armstrong** [comment]
Sorry I missed this. I will look into it.

**Comment by leowalkling** [comment]
> @yunjeongkim It is back up and running [here](https://qtcreator-ros.datasys.swri.edu/). I will close this issue once I update the wiki.

Unfortunately, I can't access it because of missing permisions.

**Comment by leowalkling** [comment]
I can access it now.
Thanks!

**Comment by Vonstafenberg** [comment]
I downloaded the [file](https://qtcreator-ros.datasys.swri.edu/downloads/installers/trusty/) for the online installer but when I run it ...the installation window is giving me a message....**Cannot retrieve remote tree**...!

**Comment by svavs** [comment]
> @Levi-Armstrong ...I downloaded the [file](https://qtcreator-ros.datasys.swri.edu/downloads/installers/xenial/) for the online installer but when I run it ...the installation window is giving me a message....**Cannot retrieve remote tree**...!...previously I installed from the [Wikipage](https://ros-industrial.github.io/ros_qtc_plugin/).... and it installed and functioned very smoothly...I hope I can do it again

Simply add a temporary repository in the installer (Configuration button) with no name, no password and path https://qtcreator-ros.datasys.swri.edu/downloads/repositories/xenial/latest/. It will work as usual.

**Comment by Vonstafenberg** [comment]
@svavs Thank you for the help, it works but then I am facing yet another error mentioned [#272](https://github.com/ros-industrial/ros_qtc_plugin/issues/272)...**Cannot create link from** .... @Levi-Armstrong .... the installation works even in-spite of the error **Cannot create link from**......Qt does not crash on creating a new ROS project or importing an existing one, yet it crashes on clicking Help. The directory `/home......./.local/bin` does exit but requires root privileges. Installing Qt offline /online installer as a root creates the ros link `qtcreator-ros` in `bin`....but then to launch Qt it has to be through sudo (terminal) or nautlius (icon launch)..... if install without root privileges, then link is not created in `bin`...but Qt still works. I am using Ubuntu 16.04 and ROS Kinetic. I hope these issues are looked into.

**Comment by svavs** [comment]
@Vonstafenberg I don't have this problem. The link is correctly created on both Ubuntu 16.04 and 18.04 (installing as non root, under the user home directory). 
The Help crash is a known bug (#289 and #277).

**Comment by Vonstafenberg** [comment]
@svavs .... this is strange since I did a fresh installation of Ubuntu and ROS a few days ago....the problem persisted for me  after the installation...! I wonder if it has anything to do with the installation of Ubuntu...?  and for the `Help` crash... so ok....its a bug already [ known](https://github.com/ros-industrial/ros_qtc_plugin/issues/289).

**Comment by svavs** [comment]
@Vonstafenberg maybe. Mine are upgrades from previous distro versions, not clean installations.

**Comment by Levi-Armstrong** [comment]
New version is available for download!

**Comment by lucascoelhof** [comment]
I'm having the same problems, seems that the server is offline.

**Comment by lucascoelhof** [comment]
I have noticed that my problem is actually a bit different, I will open another issue.

**Comment by Levi-Armstrong** [comment]
@lucascoelhof What issue are you having with the installer?

**Comment by jimitrupani** [comment]
> > @Levi-Armstrong ...I downloaded the [file](https://qtcreator-ros.datasys.swri.edu/downloads/installers/xenial/) for the online installer but when I run it ...the installation window is giving me a message....**Cannot retrieve remote tree**...!...previously I installed from the [Wikipage](https://ros-industrial.github.io/ros_qtc_plugin/).... and it installed and functioned very smoothly...I hope I can do it again
> 
> Simply add a temporary repository in the installer (Configuration button) with no name, no password and path https://qtcreator-ros.datasys.swri.edu/downloads/repositories/xenial/latest/. Also disable the Default one. It will work as usual.
![add](https://user-images.githubusercontent.com/7580176/69021896-68460e00-09df-11ea-82bb-7e921ba8d3fc.png)
![adding](https://user-images.githubusercontent.com/7580176/69021897-68dea480-09df-11ea-86c8-9f148d4058ba.png)
![done](https://user-images.githubusercontent.com/7580176/69021898-68dea480-09df-11ea-838d-acc0c81c968f.png)
![Installer](https://user-images.githubusercontent.com/7580176/69021899-68dea480-09df-11ea-8b7f-20e7694a3cfc.png)
![repo](https://user-images.githubusercontent.com/7580176/69021900-69773b00-09df-11ea-80b4-febaec603007.png)
![settings](https://user-images.githubusercontent.com/7580176/69021901-69773b00-09df-11ea-8d6e-1e41aa564044.png)


well, thanks for the suggestion. it worked like a charm.

**Comment by bekirbostanci** [comment]
I have same problem i tried add repo this link https://qtcreator-ros.datasys.swri.edu/downloads/repositories/xenial/latest/ but problem is not solved and give this error 
Cannot open Updates.xml for reading: No file name specified

**Comment by Salman-F** [comment]
@bekirbostanci U solved this problem?

**Comment by Levi-Armstrong** [comment]
@Salman-F Does the Debian attached to the release or snap not work for you?

**Comment by Salman-F** [comment]
@Levi-Armstrong the online installer and snap did not work for me. For more information watch this thread #465
