### ISSUE TITLE
QtCreator GUI blocking/freeze

### ISSUE THREAD

**Issue by christian-rauch** [ros-industrial/ros_qtc_plugin#314]
It happens often to me that the whole QtCreator GUI blocks (freeze) when using the plugin. This happens with version 4.5 and 4.8 (installed using the online installer). I've never encountered this on a plain QtCreator.

The blocking usually happens shortly after compiling the workspace inside the GUI, but I also saw it when changing the workspace, e.g. doing a git pull on some of its repos. It appears that through scanning updated files, the whole GUI thread is blocked.

**Comment by Levi-Armstrong** [comment]
Yea there are a few places I need to spin out into a separate thread.

**Comment by Levi-Armstrong** [comment]
This should be addressed by #322.

**Comment by christian-rauch** [comment]
Thank you! A very appreciated improvement to the user interface :-)

**Comment by christian-rauch** [comment]
Workspaces load much faster now and the GUI doesn't block after a build. But I still see freezes after the workspace has been loaded and the notification "Reading Project <name>" appears.

**Comment by Levi-Armstrong** [comment]
I will look into it and get back to you.

**Comment by christian-rauch** [comment]
This issue is related to the number of files in the workspace.
I used the plugin with two workspaces, let's call them `A` and `B`.
Workspace `A` contains around 50 "normal" packages and behaves as expected when using Qt Creator with the plugin, e.g. there are no freezes after compiling or when scanning files.
Workspace `B` only contains 10 packages, but one of its packages was used to store results in form of images and contains 900k files (~2GB in total), but did not contain a CMake file or likewise scripts to compile nodes. After compiling the workspace with the plugin or after saving changes to C++ files, the Qt Creator GUI freezes for at least a minute. After removing this package, the plugin also behaves correctly for workspace `B`.

I assume that the plugin scans all files in the workspace for changes, rather than only those related to compiling ROS nodes.
